# Generated by Django 4.2.6 on 2023-12-28 02:22

import admin_kit.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0003_alter_area_area_description_alter_area_area_eid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_title', models.CharField(default='None', max_length=60, verbose_name='キャスト名・店舗名')),
                ('bar_eid', models.CharField(blank=True, max_length=40, null=True, verbose_name='キャスト名・店舗名 (English)')),
                ('bar_main_image', models.ImageField(blank=True, null=True, upload_to='bars/')),
                ('bar_phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='電話')),
                ('bar_gongij', models.TextField(blank=True, null=True, verbose_name='お知らせ')),
                ('bar_events', models.TextField(blank=True, null=True, verbose_name='最新イベント')),
                ('bar_system_worktime', models.CharField(blank=True, max_length=60, null=True, verbose_name='システム - 営業時間')),
                ('bar_system_rest', models.CharField(blank=True, max_length=60, null=True, verbose_name='システム - 定休日')),
                ('bar_system_pay', models.CharField(blank=True, max_length=60, null=True, verbose_name='システム - 料金システム')),
                ('bar_system_tax', models.CharField(blank=True, max_length=60, null=True, verbose_name='システム - TAX')),
                ('bar_quiren', models.TextField(blank=True, null=True, verbose_name='求人')),
                ('bar_vorder', models.IntegerField(default=0, null=True, verbose_name='現時点で')),
                ('bar_map_url', models.URLField(blank=True, verbose_name='地図情報')),
            ],
        ),
        migrations.CreateModel(
            name='Bar_Amusement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_amusement_title', models.CharField(max_length=50, verbose_name='アミューズメント')),
                ('bar_amusement_eid', models.CharField(max_length=30, verbose_name='アミューズメント (English)')),
                ('bar_amusement_description', models.TextField(verbose_name='現時点で')),
            ],
        ),
        migrations.CreateModel(
            name='Bar_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_category_title', models.CharField(max_length=30, verbose_name='ジャンル')),
                ('bar_category_eid', models.CharField(max_length=30, verbose_name='ジャンル (English)')),
                ('bar_category_description', models.TextField(verbose_name='現時点で')),
            ],
        ),
        migrations.CreateModel(
            name='Bar_Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_facility_title', models.CharField(max_length=30, verbose_name='施設タイプ')),
                ('bar_facility_eid', models.CharField(max_length=30, verbose_name='施設タイプ (English)')),
                ('bar_facility_description', models.TextField(verbose_name='現時点で')),
            ],
        ),
        migrations.CreateModel(
            name='Bar_Fk_Casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_recorddate', models.DateField(null=True)),
                ('bar_expiredate', models.DateField(null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentmethod_title', models.CharField(max_length=50, verbose_name='支払い方法')),
                ('paymentmethod_eid', models.CharField(max_length=50, verbose_name='支払い方法 (English)')),
                ('paymentmethod_description', models.TextField(verbose_name='現時点で')),
            ],
        ),
        migrations.CreateModel(
            name='Temp_bar_cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barid', models.IntegerField(null=True, verbose_name=5)),
                ('castid', models.IntegerField(null=True, verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(default='', max_length=30, verbose_name='キャスト名')),
                ('cast_sex', admin_kit.models.SelectField(ajax_source=None, choices=[(0, '男'), (1, '女')], default_value=None, identifier=None, kit_config={}, source_router=None, verbose_name='性別')),
                ('cast_birthday', models.DateField(null=True, verbose_name='誕生日')),
                ('cast_blood', admin_kit.models.SelectField(ajax_source=None, choices=[(0, 'O型'), (1, 'A型'), (2, 'B型'), (3, 'AB型')], default=0, default_value=0, identifier=None, kit_config={}, source_router=None, verbose_name='血液型')),
                ('cast_horoscope', models.CharField(max_length=20, null=True)),
                ('cast_mobilephone', models.CharField(max_length=30, null=True, verbose_name='携帯電話番号')),
                ('cast_homephone', models.CharField(max_length=30, null=True, verbose_name='家電番号')),
                ('cast_address', models.CharField(default='', max_length=100, verbose_name='住所')),
                ('cast_height', models.FloatField(null=True, verbose_name='身長')),
                ('cast_weight', models.FloatField(null=True, verbose_name='体重')),
                ('cast_tw', models.CharField(max_length=30, null=True)),
                ('cast_tiktok', models.CharField(max_length=30, null=True)),
                ('cast_lin', models.CharField(max_length=30, null=True)),
                ('cast_instag', models.CharField(max_length=30, null=True)),
                ('cast_description', models.TextField(null=True, verbose_name='現時点で')),
                ('cast_image', models.ImageField(blank=True, null=True, upload_to='casts/')),
                ('fk_bars', models.ManyToManyField(through='bars.Bar_Fk_Casts', to='bars.bar')),
            ],
        ),
        migrations.CreateModel(
            name='Bar_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_room_label', models.CharField(max_length=10, null=True)),
                ('bar_room_name', models.CharField(max_length=60, null=True)),
                ('bar_room_description', models.TextField()),
                ('bar_room_main_image', models.ImageField(upload_to='bars/')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar')),
            ],
        ),
        migrations.AddField(
            model_name='bar_fk_casts',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.cast'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_amusements',
            field=models.ManyToManyField(to='bars.bar_amusement'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_casts',
            field=models.ManyToManyField(through='bars.Bar_Fk_Casts', to='bars.cast'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_categorys',
            field=models.ManyToManyField(to='bars.bar_category'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_facilitys',
            field=models.ManyToManyField(to='bars.bar_facility'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_paymentmethods',
            field=models.ManyToManyField(to='bars.paymentmethod'),
        ),
        migrations.AddField(
            model_name='bar',
            name='fk_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.province', verbose_name='都道府県選択'),
        ),
    ]
