# Generated by Django 4.2.6 on 2023-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='cast_image',
            field=models.ImageField(blank=True, upload_to='casts/'),
        ),
    ]
