# Generated by Django 4.2.6 on 2023-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_cast_cast_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_image',
            field=models.ImageField(blank=True, null=True, upload_to='casts/'),
        ),
    ]
