# Generated by Django 4.2.6 on 2023-12-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_alter_cast_cast_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='bar_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='bars/'),
        ),
    ]
